### ISSUE TITLE
Create Speaker Model

### ISSUE THREAD

**Issue by bketelsen** [gopheracademy/gcon#10]
Speaker Model

First Name: Brian
Last Name: Ketelsen
Bio: Brian is a terrible speaker, but we put him on the stage for his charm and great hair.
Website: https://www.brianketelsen.com
Twitter: bketelsen
LinkedIn: http://blah
Facebook: http://blah
(other social media sites??)
Contact Phone: 555-1212 
Contact Email : spf@golang.org
Photo URL:  /assets/speakers/brian.png

**Comment by briandowns** [comment]
Resolved via #18
