### ISSUE TITLE
Create Event Model

### ISSUE THREAD

**Issue by bketelsen** [gopheracademy/gcon#11]
Event Model

Name:  After Party
Short Description:  Celebrate the opening day of GopherCon with 1500 friends
Long Description:  Each year we .... blah.... blah...
Date:
Start Time:  8:00 PM
End Time: 11:00 PM
Location Name: Bob's BBQ and Pool Hall
Location Address: 2749 Wabash Street
Location City: Denver
Location State: CO
Location ZIP: 83023
Google Maps link? GEO Coordinates?

**Comment by briandowns** [comment]
Resolved via #17
