### ISSUE TITLE
Add Auth to Admin Route

### ISSUE THREAD

**Issue by bketelsen** [gopheracademy/gcon#13]
Use markbates/goth?

**Comment by briandowns** [comment]
Goth seems legit. What providers do we need to integrate with?

**Comment by markbates** [comment]
I would think Github would be enough. @bketelsen ?

**Comment by bketelsen** [comment]
Maybe twitter too?  Hate to assume everyone has a gh username and exclude
someone

**Comment by juicemia** [comment]
I'm willing to pick this up if nobody else has.

**Comment by bketelsen** [comment]
do it!

**Comment by juicemia** [comment]
Ok, but I'm not gonna be able to pick this up over the weekend, so if someone else can finish it before Monday then go for it. :(

**Comment by willmadison** [comment]
I'll take a look at this this weekend.
