### ISSUE TITLE
add go-rice

### ISSUE THREAD

**Issue by bketelsen** [gopheracademy/gcon#38]
we're doing this the HARD way :)
add go-rice to have simple dev and production deploys!

**Comment by markbates** [comment]
https://godoc.org/github.com/markbates/buffalo/render/resolvers#RiceBox

Thankfully there's a resolver for that. :)

**Comment by briandowns** [comment]
Can you add some examples of use so I can add this stuff to the Makefile?

**Comment by markbates** [comment]
In dev and test nothing will change, except the render engine should use the rice box resolver I linked above. 

When deploying to product the Go rice took needs to be run generate Go code from the templates before the binary is built. Those compiled files should never be checked in.

**Comment by briandowns** [comment]
Would that be something to include in a Makefile "build" target?

**Comment by bketelsen** [comment]
post-success in travis.  The generated file doesn't get added to source, so we test first, then generate the rice-box, then build, then docker build.
