### ISSUE TITLE
Website Design

### ISSUE THREAD

**Issue by kiasaki** [gopheracademy/gcon#4]
I'd love to work on getting some initial HTML markup and CSS styles ready for a homepage and additional pages.

I think there is 2 main things we'd need before we can start that:

- Either a HTML template to adapt OR reuse/inspire ourself of last years gorgeous website
- Graphical assets like conference logo, icons, sponsor logos (if we already have some)

**Comment by bketelsen** [comment]
two templates committed in "original-themes"
one for public site
the other is for the admin site.

**Comment by kiasaki** [comment]
Perfect! 👍 

_We probably should take them out of the repo and upload them as zip to gdrive as discussed on slack (they are pretty heavy in git and the author might not be all too happy to see his work available in the open)_
