### ISSUE TITLE
Automate development set up

### ISSUE THREAD

**Issue by juicemia** [gopheracademy/gcon#5]
Right now after cloning, devs need to set up a postgres database before getting started.

I think it would be great to have that automated. It could be done in a Dockerfile.

**EDIT:** I'm actually gonna get this done right now, just putting it here to be organized.

**Comment by bketelsen** [comment]
excellent!  I had a start to a dockerfile, but not worth committing.
docker-compose would be even better.

**Comment by bketelsen** [comment]
it will eventually deploy on Kubernetes so might as well put it all in docker now.

**Comment by bketelsen** [comment]
Let's use grift tasks for our "makefile"
see github.com/markbates/gobuffalo for inspiration

**Comment by juicemia** [comment]
I've already started with docker compose. I have a DB service working. Currently working on setting up an API dev service that runs `buffalo dev`.

**Comment by juicemia** [comment]
I've added a compose service for the dev environment, but buffalo isn't refreshing on save when run in the container. I haven't submitted a pull request for this yet because even though I already have the db automation in place I feel it's incomplete without using compose for buffalo dev as well.

Let me know if I've gone astray on this.

**Comment by markbates** [comment]
`buffalo dev` wraps the `github.com/fsnotify/fsnotify' package to watch for file system changes. Not sure how well that works, if at all in Docker. You'll want to investigate that.

**Comment by briandowns** [comment]
@juicemia is this complete?
