### ISSUE TITLE
Create Sponsor Model

### ISSUE THREAD

**Issue by bketelsen** [gopheracademy/gcon#9]
Sponsor Model 

Sponsor Name : Google
Sponsor Website: https://www.google.com
Sponsor Description : Google invented Go and is happy to sponsor Gophercon 2017
Sponsor Contact Name:  Steve Francia
Sponsor Contact Phone: 555-1212
Sponsor Contact Email : spf@golang.org
Sponsor Logo Path(or URL?) : /assets/sponsors/platinum/google.png

**Comment by briandowns** [comment]
I can take this one.

**Comment by briandowns** [comment]
I might be doing something wrong but I'm getting access denied when trying to push a branch up. Should I have forked instead?

**Comment by bketelsen** [comment]
invited you as collaborator
try again after accepting

**Comment by briandowns** [comment]
Confirmed. Thanks!

**Comment by briandowns** [comment]
Resolved via #16
